version: '2'
services:
    monthly_budget-mongodb:
        image: mongo:4.0.2
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/monthly_budget/mongodb/:/data/db/
